### ISSUE TITLE
Apple logo no boot

### ISSUE THREAD

**Issue by CAPSBOY** [kidonng/HP-Pavilion-13-Hackintosh#2]
Hi I have that laptop with the same specs and get a large apple logo and no boot .. reset nvram too.

Cheers

**Comment by kidonng** [comment]
Did you read the notes? https://github.com/kidonng/HP-Pavilion-13-Hackintosh#notes

Please provide error message booting in verbose mode, by add `-v` to `boot-args`.

**Comment by CAPSBOY** [comment]
> Did you read the notes? https://github.com/kidonng/HP-Pavilion-13-Hackintosh
> 
> Please provide error message booting in verbose mode, by add `-v` to `boot-args`.

Awesome I’ll post a -v log for you when I get a chance and check and double check your notes

**Comment by CAPSBOY** [comment]
changing the first thing in your notes worked .. thanks again

**Comment by kidonng** [comment]
Glad it helped. Also make sure to use different `PlatformInfo` values (Serial, ROM, etc.). Have fun.
